# Generated by Django 5.1.3 on 2024-12-02 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 5, 45, 36, 963673)),
        ),
    ]
