# Generated by Django 5.1.3 on 2024-12-02 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='delete',
            new_name='deleted',
        ),
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 6, 11, 8, 531405)),
        ),
    ]
