# Generated by Django 5.1.3 on 2024-12-04 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_delete_student_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 8, 36, 45, 813935)),
        ),
    ]
